package com.lumora.pos.sale;

import jakarta.validation.Valid;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * A sale as the terminal rang it up.
 *
 * <p>The money arrives already computed. That is deliberate: VAT extraction and rounding live in
 * exactly one place ({@code @lumora/domain}), and recomputing them here in Java would be the second
 * implementation the whole design exists to avoid — the one that eventually disagrees with the
 * printed receipt by a rupee. What the customer was charged is what the receipt says, and this
 * endpoint records it.
 *
 * <p>The backend still checks the arithmetic is internally consistent (see {@code SaleService}).
 * That is a checksum, not a second opinion — including for {@code tenders}, {@code
 * roundingAdjustmentMinor} and {@code changeMinor}, all of which came out of {@code
 * summariseTender} on the terminal and are trusted the same way the cart totals are.
 *
 * @param clientUuid generated by the terminal before the request is sent, so a retry is safe
 * @param roundingAdjustmentMinor {@code cashPayable − cashOwed} from {@code summariseTender}. May
 *     be negative when cash rounded down and the shop absorbed the fraction — never on the sale
 *     total itself (M1-03).
 * @param changeMinor what was handed back to the customer. Never negative.
 * @param tenders one line per payment instrument. More than one only when the sale was split
 *     (M1-11) — most sales carry exactly one.
 */
public record CreateSaleRequest(
        @NotNull UUID clientUuid,
        @NotBlank String branchCode,
        @NotBlank String terminalCode,
        Instant soldAt,
        @NotNull @Pattern(regexp = "INCLUSIVE|EXCLUSIVE") String taxMode,
        @NotNull @Min(0) Integer taxRateBp,
        @NotNull @Min(0) Long subtotalMinor,
        @NotNull @Min(0) Long discountMinor,
        @NotNull @Min(0) Long taxMinor,
        @NotNull @Min(0) Long totalMinor,
        @NotEmpty @Valid List<Line> lines,
        @NotNull Long roundingAdjustmentMinor,
        @NotNull @Min(0) Long changeMinor,
        @NotEmpty @Valid List<Tender> tenders) {

    public record Line(
            @NotNull UUID productClientUuid,
            @NotNull @Min(1) Integer qty,
            @NotNull @Min(0) Long unitPriceMinor,
            @NotNull @Min(0) Long discountMinor,
            @NotNull @Min(0) Long taxMinor,
            @NotNull @Min(0) Long lineTotalMinor) {}

    /**
     * @param amountMinor for {@code CASH}, what the customer physically handed over — may exceed
     *     what cash owed, which is where {@code changeMinor} comes from. For every other kind, the
     *     exact amount charged.
     */
    public record Tender(
            @NotNull @Pattern(regexp = "CASH|CARD|WALLET|STORE_CREDIT") String kind,
            @NotNull @Min(0) Long amountMinor) {}
}
