package com.lumora.pos.sale;

import jakarta.validation.Valid;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * A sale as the terminal rang it up.
 *
 * <p>The money arrives already computed. That is deliberate: VAT extraction and rounding live in
 * exactly one place ({@code @lumora/domain}), and recomputing them here in Java would be the second
 * implementation the whole design exists to avoid — the one that eventually disagrees with the
 * printed receipt by a rupee. What the customer was charged is what the receipt says, and this
 * endpoint records it.
 *
 * <p>The backend still checks the arithmetic is internally consistent (see {@code SaleService}).
 * That is a checksum, not a second opinion — including for {@code tenders}, {@code
 * roundingAdjustmentMinor} and {@code changeMinor}, all of which came out of {@code
 * summariseTender} on the terminal and are trusted the same way the cart totals are.
 *
 * <p>Since M1-18 each {@link Line} may carry its own {@code taxMode} / {@code taxRateBp}, and
 * the sale-level pair is the default the lines inherit rather than a summary of them. A sale
 * mixing an exempt line with an 18% one is now ordinary; what tells you the tax charged is
 * {@code Σ line.taxMinor}, which is why {@code SaleService} now checks exactly that.
 *
 * @param clientUuid generated by the terminal before the request is sent, so a retry is safe
 * @param roundingAdjustmentMinor {@code cashPayable − cashOwed} from {@code summariseTender}. May
 *     be negative when cash rounded down and the shop absorbed the fraction — never on the sale
 *     total itself (M1-03).
 * @param changeMinor what was handed back to the customer. Never negative.
 * @param tenders one line per payment instrument. More than one only when the sale was split
 *     (M1-11) — most sales carry exactly one.
 * @param customerClientUuid who the sale was for, or null (M3-11). Null is the normal case and
 *     stays that way: the overwhelming majority of sales in a grocery are anonymous, and a
 *     required customer would be a prompt between the last item and the drawer opening.
 *     <p>Attaching one changes nothing about the money. That is a v1 decision, not an oversight —
 *     the moment a customer can change what is charged, a mis-tap at the till stops being a wrong
 *     name on a receipt and becomes a pricing error. Loyalty and credit arrive with the question
 *     of what they are allowed to move.
 */
public record CreateSaleRequest(
        @NotNull UUID clientUuid,
        @NotBlank String branchCode,
        @NotBlank String terminalCode,
        Instant soldAt,
        @NotNull @Pattern(regexp = "INCLUSIVE|EXCLUSIVE") String taxMode,
        @NotNull @Min(0) Integer taxRateBp,
        @NotNull @Min(0) Long subtotalMinor,
        @NotNull @Min(0) Long discountMinor,
        @NotNull @Min(0) Long taxMinor,
        @NotNull @Min(0) Long totalMinor,
        @NotEmpty @Valid List<Line> lines,
        @NotNull Long roundingAdjustmentMinor,
        @NotNull @Min(0) Long changeMinor,
        @NotEmpty @Valid List<Tender> tenders,
        UUID customerClientUuid) {

    /**
     * @param taxMode this line's own tax treatment, or {@code null} to inherit the sale's
     *     (M1-18). Nullable on purpose: before M1-18 a line carried no stamp at all because a
     *     cart could only hold one rate, and a terminal that has not been upgraded still sends
     *     that shape. Inheriting reproduces exactly what such a till meant.
     * @param taxRateBp as above. Always inherited together with {@code taxMode} — a line
     *     specifying one and not the other is rejected rather than half-inherited.
     */
    public record Line(
            @NotNull UUID productClientUuid,
            @NotNull @Min(1) Integer qty,
            @NotNull @Min(0) Long unitPriceMinor,
            @NotNull @Min(0) Long discountMinor,
            @NotNull @Min(0) Long taxMinor,
            @NotNull @Min(0) Long lineTotalMinor,
            @Pattern(regexp = "INCLUSIVE|EXCLUSIVE") String taxMode,
            @Min(0) Integer taxRateBp) {

        /** The pre-M1-18 shape, for callers with one rate for the whole sale. */
        public Line(
                UUID productClientUuid,
                Integer qty,
                Long unitPriceMinor,
                Long discountMinor,
                Long taxMinor,
                Long lineTotalMinor) {
            this(productClientUuid, qty, unitPriceMinor, discountMinor, taxMinor, lineTotalMinor, null, null);
        }

        /** This line's stamp, falling back to the sale's where the terminal sent none. */
        public String effectiveTaxMode(CreateSaleRequest sale) {
            return taxMode != null ? taxMode : sale.taxMode();
        }

        public Integer effectiveTaxRateBp(CreateSaleRequest sale) {
            return taxRateBp != null ? taxRateBp : sale.taxRateBp();
        }
    }

    /**
     * @param amountMinor for {@code CASH}, what the customer physically handed over — may exceed
     *     what cash owed, which is where {@code changeMinor} comes from. For every other kind, the
     *     exact amount charged.
     */
    public record Tender(
            @NotNull @Pattern(regexp = "CASH|CARD|WALLET|STORE_CREDIT") String kind,
            @NotNull @Min(0) Long amountMinor) {}
}
