package com.lumora.pos.auth;

import java.security.SecureRandom;
import java.util.Base64;
import java.util.List;
import java.util.UUID;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * The key this till signs its session tokens with (M3-09).
 *
 * <h2>Provisioned here, not configured</h2>
 *
 * A key in {@code application.yml} is the same key in every copy of this build, so a token minted
 * on one shop's PC would verify on another's. A key in an environment variable is a key somebody
 * has to remember to set, and the failure mode of that is a default nobody changed. So the key is
 * 32 bytes from {@link SecureRandom}, generated by this machine the first time it is needed, and
 * written to the machine's own database. It never leaves.
 *
 * <p>M5-03's first-run wizard will provision it during activation. That is the same act at a
 * tidier moment, and this class is what it will call — creating it lazily now means a till that
 * upgrades into M3-09 works on the next boot rather than needing a re-activation.
 *
 * <h2>Rotation, and why tokens carry a kid</h2>
 *
 * {@link #rotate} inserts a new active key and retires the old one. Tokens already in a cashier's
 * hands were signed by the retired key and keep verifying against it until they expire — minutes,
 * not hours. Without the {@code kid} header naming which key signed a token, rotating would sign
 * everybody out at once, which is the kind of thing that makes a shop stop rotating.
 */
@Component
public class SigningKeyStore {

    /** HS256. Signing and verification happen in the same process, on the same machine. */
    private static final int KEY_BYTES = 32;

    private final JdbcTemplate jdbc;
    private final SecureRandom random = new SecureRandom();

    public SigningKeyStore(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    /** A key, ready to sign or verify with. */
    public record Key(String kid, SecretKey material) {}

    /**
     * The key to sign new tokens with, creating one if this till has never had a session.
     *
     * <p>Two boots racing to create the first key would both insert, and then {@code
     * ux_signing_keys_one_active} would fail one of them — which is the correct outcome and not a
     * useful error, so the loser re-reads instead of surfacing a constraint violation to whoever
     * was signing in.
     */
    @Transactional
    public Key active() {
        Key existing = readActive();
        if (existing != null) {
            return existing;
        }
        try {
            return insert();
        } catch (org.springframework.dao.DuplicateKeyException raced) {
            Key winner = readActive();
            if (winner == null) {
                throw raced;
            }
            return winner;
        }
    }

    /**
     * Finds the key a token names in its {@code kid}, active or retired.
     *
     * <p>Retired keys verify. That is the whole point of the kid: a rotation must not invalidate
     * tokens that were legitimately issued a minute earlier. What stops a retired key being useful
     * to an attacker is the token's own expiry, which is short, and the session row, which a
     * rotation can revoke if the rotation happened because the key leaked.
     */
    public Key byKid(String kid) {
        if (kid == null || kid.isBlank()) {
            return null;
        }
        List<Key> found =
                jdbc.query(
                        "SELECT kid, secret FROM signing_keys WHERE kid = ?",
                        (rs, row) -> toKey(rs.getString("kid"), rs.getString("secret")),
                        kid);
        return found.isEmpty() ? null : found.get(0);
    }

    /**
     * Retires the current key and provisions a new one. Sessions are left alone — see the class
     * note; revoking them is a separate decision that belongs to whoever decided to rotate.
     */
    @Transactional
    public Key rotate() {
        jdbc.update("UPDATE signing_keys SET active = false, retired_at = now() WHERE active");
        return insert();
    }

    private Key insert() {
        byte[] secret = new byte[KEY_BYTES];
        random.nextBytes(secret);
        String kid = UUID.randomUUID().toString();
        String encoded = Base64.getEncoder().encodeToString(secret);
        jdbc.update("INSERT INTO signing_keys (kid, secret) VALUES (?, ?)", kid, encoded);
        return new Key(kid, new SecretKeySpec(secret, "HmacSHA256"));
    }

    private Key readActive() {
        List<Key> found =
                jdbc.query(
                        "SELECT kid, secret FROM signing_keys WHERE active",
                        (rs, row) -> toKey(rs.getString("kid"), rs.getString("secret")));
        return found.isEmpty() ? null : found.get(0);
    }

    private static Key toKey(String kid, String secret) {
        return new Key(kid, new SecretKeySpec(Base64.getDecoder().decode(secret), "HmacSHA256"));
    }
}
