// The update channel, and the three things it refuses to do (M5-11).
//
// ## Why a till needs this at all
//
// M5-01 ships one 178 MB installer and M5-02 makes it a double-click. What neither answers is the
// second release. Without a channel, every fix reaches a shop as a phone call, a download link and
// a person who has to be talked through running an installer over their own POS — which is how a
// shop ends up two years behind on a product whose whole promise is that it keeps working.
//
// ## It never installs while the app is running, and that is the design
//
// `autoInstallOnAppQuit`, and `quitAndInstall()` is never called. Not "we try not to interrupt a
// sale" — there is no code path that can. An update is downloaded quietly and applied the next time
// the shop closes StoreX, which for a grocery is the end of the day.
//
// The alternative that every desktop app ships — "restart now to update" — is unacceptable here for
// a reason that is specific to this product. A till is not a browser. Somebody is standing at it
// with a queue, and a restart mid-shift means Postgres stopping under an open shift, an unprinted
// receipt, and a cashier who now distrusts the machine. Nothing that is not the sale may ever
// interrupt the sale; that rule already governs the printer, the outbox and the backups.
//
// ## It refuses to run unsigned, and this is not caution
//
// An update channel is, by construction, remote code execution on every shop PC in the country.
// The only thing standing between it and somebody who can answer for that URL is the Authenticode
// signature check `electron-updater` performs on the downloaded installer — and that check exists
// only when the app was signed with a publisher name to compare against. An unsigned channel is not
// "an update channel with a SmartScreen warning". It is an open door.
//
// So `updateDecision` below refuses without a publisher name, and says why in a log line somebody
// will actually find. The override exists for a developer testing the mechanics against a local
// feed and is named so that nobody reaches for it by accident on a shop's machine.
//
// ## https only
//
// The same argument one step earlier: over http, the door does not even need a key.

const fs = require('node:fs');
const path = require('node:path');

const { trace } = require('./runtimeConfig.cjs');

/**
 * Six hours.
 *
 * A shop is open for ten or twelve, so this asks about twice a trading day. Anything faster is
 * bandwidth spent on an answer that changes a handful of times a year; anything slower and a fix
 * shipped on Monday reaches a shop that opens six days a week some time on Wednesday.
 */
const CHECK_INTERVAL_MS = 6 * 60 * 60 * 1000;

/**
 * Ten minutes after launch.
 *
 * Later than the backup's five, and for the same reason ordered further back: the morning is the
 * busiest thing this process does, and a 178 MB download competing with a shop's first hour is
 * felt by the cashier and by nobody else.
 */
const FIRST_CHECK_DELAY_MS = 10 * 60 * 1000;

/**
 * Whether this build may update itself, and the sentence explaining the answer.
 *
 * Pure, and separated from everything that touches Electron, because this is the whole security
 * decision of the feature and a decision worth testing is a decision worth being able to call.
 *
 * @param {{url: string|null, packaged: boolean, publisherName: string|null, allowUnsigned: boolean}} state
 * @returns {{enabled: boolean, reason: string}}
 */
function updateDecision(state) {
  if (!state.packaged) {
    return { enabled: false, reason: 'not a packaged build' };
  }
  if (!state.url) {
    return { enabled: false, reason: 'no LUMORA_UPDATE_URL is set' };
  }
  let parsed;
  try {
    parsed = new URL(state.url);
  } catch {
    return { enabled: false, reason: `LUMORA_UPDATE_URL is not a URL: ${state.url}` };
  }
  if (parsed.protocol !== 'https:') {
    return {
      enabled: false,
      reason: `the update feed must be https, not ${parsed.protocol.replace(':', '')}`,
    };
  }
  if (!state.publisherName) {
    if (!state.allowUnsigned) {
      return {
        enabled: false,
        reason:
          'this build is not code-signed, so a downloaded update cannot be verified. ' +
          'An unverified update channel is remote code execution on every till. ' +
          'Sign the build, or set LUMORA_UPDATE_ALLOW_UNSIGNED=1 on a development machine only',
      };
    }
    return { enabled: true, reason: 'ENABLED WITHOUT SIGNATURE VERIFICATION — development only' };
  }
  return { enabled: true, reason: `verifying against publisher "${state.publisherName}"` };
}

/**
 * The publisher name electron-builder baked into the packaged app, or null.
 *
 * Read with a line match rather than a YAML parser. `app-update.yml` is generated by
 * electron-builder from our own build config and is three or four flat keys; pulling in a parser to
 * read one of them would add a dependency to the one code path that must not surprise anybody. If
 * the file is missing — an unpacked run, a build without a publisher — the answer is null, which is
 * the safe answer.
 */
function packagedPublisherName(resourcesPath) {
  try {
    const file = path.join(resourcesPath, 'app-update.yml');
    const found = fs
      .readFileSync(file, 'utf8')
      .split(/\r?\n/)
      .map((line) => /^publisherName:\s*(.+?)\s*$/.exec(line))
      .find(Boolean);
    if (!found) return null;
    // Either a bare scalar or a one-element inline list, which is how electron-builder writes it
    // when `win.publisherName` is an array.
    const value = found[1]
      .replace(/^\[\s*/, '')
      .replace(/\s*\]$/, '')
      .replace(/^["']|["']$/g, '');
    return value.trim() === '' ? null : value.trim();
  } catch {
    return null;
  }
}

/**
 * Starts the channel. Returns a stop function, or null when it is not running.
 *
 * Every failure here is logged and swallowed. A till that cannot reach its update feed is a till
 * that keeps selling on the version it has, which is the correct behaviour and the same one the
 * outbox and the backup schedule already have.
 *
 * @param {{isPackaged: boolean, resourcesPath: string}} shell what Electron knows, passed in rather
 *   than imported, so this file can be loaded and reasoned about without an Electron process.
 * @param {(event: {status: string, version?: string}) => void} onChange told when there is
 *   something the person at the till should know — which is only ever "an update is ready and will
 *   be applied when you next close StoreX".
 */
function startSchedule(shell, onChange) {
  const decision = updateDecision({
    url: process.env.LUMORA_UPDATE_URL || null,
    packaged: shell.isPackaged,
    publisherName: packagedPublisherName(shell.resourcesPath),
    allowUnsigned: process.env.LUMORA_UPDATE_ALLOW_UNSIGNED === '1',
  });

  trace(`updater: ${decision.enabled ? 'on' : 'off'} — ${decision.reason}`);
  if (!decision.enabled) {
    return null;
  }

  let updater;
  try {
    updater = require('electron-updater').autoUpdater;
  } catch (e) {
    trace(`updater: could not load electron-updater — ${e.message}`);
    return null;
  }

  updater.autoDownload = true;
  // The line this whole file is arranged around. Nothing else may install an update.
  updater.autoInstallOnAppQuit = true;
  updater.logger = {
    info: (m) => trace(`updater: ${m}`),
    warn: (m) => trace(`updater: ${m}`),
    error: (m) => trace(`updater: ${m}`),
    debug: () => {},
  };
  updater.setFeedURL({ provider: 'generic', url: process.env.LUMORA_UPDATE_URL });

  updater.on('update-downloaded', (info) => {
    trace(`updater: ${info.version} downloaded, will install on quit`);
    onChange({ status: 'ready', version: info.version });
  });
  updater.on('error', (e) => {
    // Including every offline shop, twice a day, forever. Never surfaced to the cashier: an update
    // that did not happen is not news, and a till that nags about its internet is a till whose
    // warnings stop being read.
    trace(`updater: check failed — ${e.message}`);
  });

  let timer = null;
  let stopped = false;
  const check = () => {
    if (stopped) return;
    updater.checkForUpdates().catch(() => {
      // Already reported through the error handler above.
    });
  };

  timer = setTimeout(function repeat() {
    check();
    if (!stopped) timer = setTimeout(repeat, CHECK_INTERVAL_MS);
  }, FIRST_CHECK_DELAY_MS);

  return () => {
    stopped = true;
    if (timer) clearTimeout(timer);
  };
}

module.exports = {
  startSchedule,
  updateDecision,
  packagedPublisherName,
  CHECK_INTERVAL_MS,
  FIRST_CHECK_DELAY_MS,
};
